name: Clang Format Test

on:
  push:
    paths:
      - '**/*.c'
      - '.clang-format'
  workflow_dispatch:

jobs:
  clang-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up clang-format
        run: sudo apt-get install clang-format

      - name: Run clang-format test script
        run: chmod +x ./test/format_check.sh